### ISSUE TITLE
How to schedule a notification that will repeat with some frequency after specific time passes

### ISSUE THREAD

**Issue by mibrahim025** [d7laungani/DLLocalNotifications#15]
I don't see support for scheduling such kind of notification i.e. that repeats only when a specific time passes. The problem is that the schedule fires immediately without waiting for the exact time although repeats correctly.

e.g. here is the code for scheduling a repeating notification after 10 minutes. This doesn't wait for the 10 minutes - fires immediately in the next minute from now.

        let triggerDate = Date().addingTimeInterval(600)
        let firstNotification = DLNotification(identifier: "firstNotification", alertTitle: "Notification Alert",                        alertBody: "You have successfully created a notification", date: triggerDate, repeats: .Minute)
        
        let scheduler = DLNotificationScheduler()
        scheduler.scheduleNotification(notification: firstNotification)

here is another block of code for a repeating notification that will fire daily after 3 days.

        let triggerDate = Date().addingTimeInterval(3*24*60*60)
        let firstNotification = DLNotification(identifier: "firstNotification", alertTitle: "Notification Alert", alertBody: "You have successfully created a notification", date: triggerDate, repeats: .Daily)
        
        let scheduler = DLNotificationScheduler()
        scheduler.scheduleNotification(notification: firstNotification)`

This also doesn't wait for the 3 days but fires immediately on the next day.

The main problem in both is that **it ignores the time till which it should wait to start firing the notification.** If anybody has understood the problem, will you take some time to figure out what's wrong. I will be really thankful.

**Comment by d7laungani** [comment]
Thank you for reporting this bug. It is fixed and I have made tests to prove it is fixed.

Check out : 

https://github.com/d7laungani/DLLocalNotifications/blob/4b2c3a20c8d38a889a920ad0e1f6e9cf57d80a9e/DLLocalNotificationsTests/DLLocalNotificationsTests.swift#L208

https://github.com/d7laungani/DLLocalNotifications/blob/4b2c3a20c8d38a889a920ad0e1f6e9cf57d80a9e/DLLocalNotificationsTests/DLLocalNotificationsTests.swift#L246

**Comment by mibrahim025** [comment]
Hi, Thanks for your struggle on fixing this issue however i have confirmed on actual device that this issue is still there. If I schedule a local notification for 3 days later from today at some time, it starts firing today as well as tomorrow(this is not as it should be) and so on - on every coming day after the actual date (this is as it should be). Can you please take a look again. Thanks for your time.
